export enum RouteListActionTypes {
	ADD_POINT = 'ADD_POINT',
	SET_CURRENT_ROUTE = 'SET_CURRENT_ROUTE',
	CHANGE_POINT_ORDER = 'CHANGE_POINT_ORDER',
	UPDATE_POINT_GEOMETRY = 'UPDATE_POINT_GEOMETRY',
	REMOVE_POINT = 'REMOVE_POINT'
};